### ISSUE TITLE
Does not compile with -std=c++17

### ISSUE THREAD

**Issue by higaski** [taocpp/tuple#1]
Currently does not compile with GCC 7.3.1 and the -std=c++17 flag. All test cases throw 'wrong number of template arguments' errors.

**Comment by d-frey** [comment]
Sorry for the delay. Can you update and try again? I made quite a few fixes and I think the "wrong number of template arguments"-errors should be gone now.

**Comment by higaski** [comment]
Yep, works like a charm now.

The tuple implementation itself is amazing btw. Its so much faster then the one from libstdc++, specially when plugged into generic algorithms like for_each.

**Comment by d-frey** [comment]
Thanks, it's good to hear that it works well for you :)
